name: CI
on: [pull_request]

jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install Ghost with dev extras
        run: pip3 install ".[dev]"
      - name: Run pytest with coverage
        run: pytest
  Linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Ghost
        run: pip3 install .
      - name: Perform checks
        run: echo 'exit' | ghost
  macOS:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Ghost
        run: pip3 install .
      - name: Perform checks
        run: echo 'exit' | ghost
